# -*- coding: utf-8 -*-
"""
Created on Thu Dec 10 09:31:40 2020

@author: pirkelma
"""
from MPaut import voxsm_subprocess

# launch VoxSM process
voxsm_comm = voxsm_subprocess.VoxSM_Communicator(executable='../bin/VoxSM_2017_x64.exe')

# load voxel file generated by GeoVal
voxsm_comm.open_voxel_file('output/voxels.val')

# output information about the voxel file
print("particles: ", voxsm_comm.get_particles())
print("materials: ", voxsm_comm.get_materials())

# split periodic particles into separate regions and generate a mesh
voxsm_comm.split_regions()
voxsm_comm.generate_mesh()

# modify the mesh: smoothing and simplification
voxsm_comm.adaptive_smooth()
stats = voxsm_comm.simplify({'runs': 0})
#voxsm_comm.adaptive_simplify(max_vertices=50000)

# output mesh in various formats
voxsm_comm.store_mesh(call_tetview=True)
voxsm_comm.store_ansys(introduce_GB_prisms=False)

voxsm_comm.close()
