# -*- coding: utf-8 -*-
"""
Created on Thu Dec 10 09:31:40 2020

@author: pirkelma
"""
from MPaut import voxsm_subprocess

# launch VoxSM process
voxsm_comm = voxsm_subprocess.VoxSM_Communicator(executable='../bin/VoxSM_2017_x64.exe')

# load voxel file generated by GeoVal
# voxsm_comm.open_voxel_file('output/voxels.val')
voxsm_comm.open_voxel_file('output/10_spheres.val')

# output information about the voxel file
voxsm_comm.print_particles()
voxsm_comm.print_materials()

# split periodic particles into separate regions and generate a mesh
voxsm_comm.split_regions()
voxsm_comm.generate_mesh()

# # modify the mesh: smoothing and simplification
# # Repeating the smooth and simplify mesh 2 times.
# '''-> do Smooth -> build Edge-Heap -> do SIMPLIFY Mesh -> do Smooth -> build Edge-Heap -> do SIMPLIFY Mesh.'''
# for i in  range(2):

voxsm_comm.smooth(iterations=100, k_BP=0.02, lambd='auto', 
                  fix_vs_nn=2.0e-7, mode='all')  
  
voxsm_comm.adaptive_smooth(eL_min_factor=0.75)

stats = voxsm_comm.simplify(option_dict={'err-(cost)-max': 1e-5,
            'runs': 5,
            'folding-min': 0.1,
            'Es-per-V-max': 12,
            'FQ-min': 0.16,
            'lmin/lmed-min': 0.22,
            'lmed^2/A-max' : 10.8,
            'FA-max': 1e-12,
            'FA-min': 1e-15,
            'eL(r4)-max': 1e-6,
            'eL(r3)-max': 4e-6,
            'eL-growFac': 5.8,
            'pinch-close-eL': True,
            'd-min': 1e-7,
            'd-fac': 0.15,
            'use-costs': True,
            'intersection-test': True,
            'r3-only': False,
            'r2-only': False,
            'bad-Fs-only': False,
            'high-cost-first': False,
            'fix-corners': False,
            'focal-point-r2': False,
            'focal-point-r3': False,})

voxsm_comm.adaptive_simplify(max_vertices=100, repeat_threshold=5)

# output mesh in various formats
voxsm_comm.store_mesh(call_tetview=True)
voxsm_comm.store_ansys(introduce_GB_prisms=False)

voxsm_comm.close()
