from .utils import wait_for_checkpoint_file

def run(mapdl):
    # 86 CMs (particles)
    mapdl.type(1)
    mapdl.cmsel("s", "c_100001")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100001", "Elem")
    mapdl.cmsel("s", "c_100002")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100002", "Elem")
    mapdl.cmsel("s", "c_100003")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100003", "Elem")
    mapdl.cmsel("s", "c_100004")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100004", "Elem")
    mapdl.cmsel("s", "c_100005")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100005", "Elem")
    mapdl.cmsel("s", "c_100006")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100006", "Elem")
    mapdl.cmsel("s", "c_100007")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100007", "Elem")
    mapdl.cmsel("s", "c_100008")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100008", "Elem")
    mapdl.cmsel("s", "c_100009")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100009", "Elem")
    mapdl.cmsel("s", "c_100010")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100010", "Elem")
    mapdl.cmsel("s", "c_100011")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100011", "Elem")
    mapdl.cmsel("s", "c_100012")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100012", "Elem")
    mapdl.cmsel("s", "c_100013")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100013", "Elem")
    mapdl.cmsel("s", "c_100014")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100014", "Elem")
    mapdl.cmsel("s", "c_100015")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100015", "Elem")
    mapdl.cmsel("s", "c_100016")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100016", "Elem")
    mapdl.cmsel("s", "c_100017")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100017", "Elem")
    mapdl.cmsel("s", "c_100018")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100018", "Elem")
    mapdl.cmsel("s", "c_100019")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100019", "Elem")
    mapdl.cmsel("s", "c_100020")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100020", "Elem")
    mapdl.cmsel("s", "c_100021")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100021", "Elem")
    mapdl.cmsel("s", "c_100022")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100022", "Elem")
    mapdl.cmsel("s", "c_100023")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100023", "Elem")
    mapdl.cmsel("s", "c_100024")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100024", "Elem")
    mapdl.cmsel("s", "c_100025")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100025", "Elem")
    mapdl.cmsel("s", "c_100026")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100026", "Elem")
    mapdl.cmsel("s", "c_100027")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100027", "Elem")
    mapdl.cmsel("s", "c_100028")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100028", "Elem")
    mapdl.cmsel("s", "c_100029")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100029", "Elem")
    mapdl.cmsel("s", "c_100030")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100030", "Elem")
    mapdl.cmsel("s", "c_100031")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100031", "Elem")
    mapdl.cmsel("s", "c_100032")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100032", "Elem")
    mapdl.cmsel("s", "c_100033")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100033", "Elem")
    mapdl.cmsel("s", "c_100034")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100034", "Elem")
    mapdl.cmsel("s", "c_100035")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100035", "Elem")
    mapdl.cmsel("s", "c_100036")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100036", "Elem")
    mapdl.cmsel("s", "c_100037")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100037", "Elem")
    mapdl.cmsel("s", "c_100038")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100038", "Elem")
    mapdl.cmsel("s", "c_100039")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100039", "Elem")
    mapdl.cmsel("s", "c_100040")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100040", "Elem")
    mapdl.cmsel("s", "c_100041")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100041", "Elem")
    mapdl.cmsel("s", "c_100042")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100042", "Elem")
    mapdl.cmsel("s", "c_100043")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100043", "Elem")
    mapdl.cmsel("s", "c_100044")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100044", "Elem")
    mapdl.cmsel("s", "c_100045")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100045", "Elem")
    mapdl.cmsel("s", "c_100046")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100046", "Elem")
    mapdl.cmsel("s", "c_100047")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100047", "Elem")
    mapdl.cmsel("s", "c_100048")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100048", "Elem")
    mapdl.cmsel("s", "c_100049")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100049", "Elem")
    mapdl.cmsel("s", "c_100050")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100050", "Elem")
    mapdl.cmsel("s", "c_100051")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100051", "Elem")
    mapdl.cmsel("s", "c_100052")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100052", "Elem")
    mapdl.cmsel("s", "c_100053")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100053", "Elem")
    mapdl.cmsel("s", "c_100054")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100054", "Elem")
    mapdl.cmsel("s", "c_100055")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100055", "Elem")
    mapdl.cmsel("s", "c_100056")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100056", "Elem")
    mapdl.cmsel("s", "c_100057")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100057", "Elem")
    mapdl.cmsel("s", "c_100058")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100058", "Elem")
    mapdl.cmsel("s", "c_100059")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100059", "Elem")
    mapdl.cmsel("s", "c_100060")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100060", "Elem")
    mapdl.cmsel("s", "c_100061")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100061", "Elem")
    mapdl.cmsel("s", "c_100062")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100062", "Elem")
    mapdl.cmsel("s", "c_100063")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100063", "Elem")
    mapdl.cmsel("s", "c_100064")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100064", "Elem")
    mapdl.cmsel("s", "c_100065")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100065", "Elem")
    mapdl.cmsel("s", "c_100066")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100066", "Elem")
    mapdl.cmsel("s", "c_100067")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100067", "Elem")
    mapdl.cmsel("s", "c_100068")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100068", "Elem")
    mapdl.cmsel("s", "c_100069")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100069", "Elem")
    mapdl.cmsel("s", "c_100070")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100070", "Elem")
    mapdl.cmsel("s", "c_100071")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100071", "Elem")
    mapdl.cmsel("s", "c_100072")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100072", "Elem")
    mapdl.cmsel("s", "c_100073")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100073", "Elem")
    mapdl.cmsel("s", "c_100074")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100074", "Elem")
    mapdl.cmsel("s", "c_100075")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100075", "Elem")
    mapdl.cmsel("s", "c_100076")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100076", "Elem")
    mapdl.cmsel("s", "c_100077")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100077", "Elem")
    mapdl.cmsel("s", "c_100078")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100078", "Elem")
    mapdl.cmsel("s", "c_100079")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100079", "Elem")
    mapdl.cmsel("s", "c_100080")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100080", "Elem")
    mapdl.cmsel("s", "c_100081")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100081", "Elem")
    mapdl.cmsel("s", "c_100082")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100082", "Elem")
    mapdl.cmsel("s", "c_100083")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100083", "Elem")
    mapdl.cmsel("s", "c_100084")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100084", "Elem")
    mapdl.cmsel("s", "c_100085")
    mapdl.mat(1)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_100085", "Elem")
    mapdl.cmsel("s", "c_200000")
    mapdl.mat(2)
    mapdl.fvmesh("keepShells")
    mapdl.esel("r", "type", "", 1)
    mapdl.cm("v_200000", "Elem")
